// AUTO-GENERATED by pipeline/scripts/convert_scenes.mjs — 원본: docs/SCRIPT/raw/c1s01.md
// 수동 편집 금지. 원고를 고치고 컨버터를 재실행할 것.

import type { Scene } from '@/engine/types';
import { FLAGS } from '@/data/flags';

export const c1s01: Scene = {
  id: "c1s01",
  title: "존재감 없는 놈",
  assets: { bgs: ["/assets/bg/bg_gate_morning.webp", "/assets/bg/bg_class_day.webp"], bgm: ["/assets/audio/bgm/bgm_daily.ogg"] },
  script: [
    { t: "set", ops: [{ key: FLAGS.AFF_SEA, op: "set", value: 0 }, { key: FLAGS.AFF_RIWON, op: "set", value: 0 }, { key: FLAGS.AFF_YUNSEUL, op: "set", value: 0 }, { key: FLAGS.LAST_CHOICE, op: "set", value: 0 }] },
    { t: "bg", src: "/assets/bg/bg_gate_morning.webp", fx: "fade" },
    { t: "bgm", src: "/assets/audio/bgm/bgm_daily.ogg" },
    { t: "say", who: null, text: "내 하루는 자기소개로 시작한다." },
    { t: "say", who: null, text: "남들은 이름을 불리는 걸로 시작하겠지만, 나는 아니다. 내가 먼저 말하지 않으면 대화가 잘 안 굴러간다." },
    { t: "say", who: null, text: "3년쯤 하다 보니 요령도 생겼다. 3초. 그 안에 치고 들어가면 된다." },
    { t: "say", who: null, text: "교문 앞. 같은 반 애가 나를 보더니 걸음을 멈췄다." },
    { t: "say", who: "mob", text: "어, 야. 저기 — 뭐였더라, 그…", expr: "surprise" },
    { t: "say", who: "haram", text: "2학년 5반이고요, 분실물 보관소 관리인이에요. 어제 우산 찾아가신 분 맞죠?", expr: "smile" },
    { t: "say", who: "mob", text: "아 맞다 맞다, 그 우산! 진짜 고마웠어. 어, 그, 관리인아.", expr: "laugh" },
    { t: "say", who: "haram", text: "접수됐습니다.", expr: "laugh" },
    { t: "say", who: null, text: "'관리인아'는 처음 들어봤다. 어감이 나쁘지 않다." },
    { t: "bg", src: "/assets/bg/bg_class_day.webp", fx: "fade" },
    { t: "say", who: null, text: "8시 40분. 담임이 출석부를 펼쳤다." },
    { t: "say", who: "mob", text: "12번 김도현. 13번 오세진. …14번.", expr: "neutral" },
    { t: "say", who: "haram", text: "네!", expr: "smile" },
    { t: "say", who: null, text: "14번에서는 반 박자 쉬고 대답해야 딱 맞는다. 3년 하면 이 정도 박자는 몸이 외운다." },
    { t: "say", who: "mob", text: "15번 유가은.", expr: "neutral" },
    { t: "say", who: null, text: "옆자리 짝이 팔꿈치로 나를 툭 쳤다." },
    { t: "say", who: "mob", text: "야, 근데 너 이름이 뭐였지. 아 미안, 진짜 미안. 한 학기를 같이 앉았는데.", expr: "worry" },
    { t: "say", who: "haram", text: "괜찮아요, 저 원래 존재감 없어서.", expr: "smile" },
    { t: "say", who: "mob", text: "야 존댓말 하지 마, 더 미안하잖아.", expr: "laugh" },
    { t: "say", who: "haram", text: "그럼 괜찮아. 존댓말은 관리인 직업병이라 그래.", expr: "laugh" },
    { t: "say", who: null, text: "짝이 웃었다. 이 농담은 타율이 좋다." },
    { t: "say", who: null, text: "노트를 폈다. 앞장 이름 칸이 또 찢겨 있었다. 세 번째다. 나는 마스킹테이프를 잘라 붙이고, 거기에 아무것도 쓰지 않았다." },
    { t: "say", who: null, text: "목이 결려서 옷깃을 당겼다. 손끝에 오래된 흉터가 걸렸다. 언제 생겼는지는 기억이 안 난다. 뭐, 그럴 수도 있지." },
    { t: "set", ops: [{ key: FLAGS.CLUE_SCAR, op: "set", value: true }] },
    { t: "jump", scene: "c1s02" },
  ],
};
