// AUTO-GENERATED by pipeline/scripts/convert_scenes.mjs — 원본: docs/SCRIPT/raw/c2s03.md
// 수동 편집 금지. 원고를 고치고 컨버터를 재실행할 것.

import type { Scene } from '@/engine/types';
import { FLAGS } from '@/data/flags';

export const c2s03: Scene = {
  id: "c2s03",
  title: "없는 사람",
  assets: { bgs: ["/assets/bg/bg_av_room.webp", "/assets/bg/bg_flowerbed.webp"], bgm: ["/assets/audio/bgm/bgm_unease.ogg"] },
  script: [
    { t: "bg", src: "/assets/bg/bg_av_room.webp", fx: "fade" },
    { t: "bgm", src: "/assets/audio/bgm/bgm_unease.ogg" },
    { t: "say", who: null, text: "시청각실 자료실은 먼지 냄새가 났다. 한쪽 벽은 오래된 DVD, 반대쪽은 라벨이 벗겨진 백업 하드가 상자째로 두 줄." },
    { t: "say", who: null, text: "이런 건 내 전공이다. 가방에서 라벨 프린터를 꺼냈다." },
    { t: "say", who: "haram", text: "일단 라벨부터 붙이자.", expr: "smile" },
    { t: "say", who: null, text: "상자 세 개를 정리했을 때 보관소 CCTV 백업이 나왔다. 비품이 자꾸 없어져서 3층 복도랑 보관소 안쪽에 카메라를 달았다고 했다. 30일치가 여기서 돌아간다." },
    { t: "say", who: null, text: "어제 방과후 구간을 찾는 데 1분도 안 걸렸다." },
    { t: "say", who: "haram", text: "어제 우리 완전 난리였는데. 이거 재밌겠는데?", expr: "laugh" },
    { t: "say", who: null, text: "화면 속에는 나 혼자 서 있었다." },
    { t: "say", who: null, text: "3분 42초 동안 나는 거의 움직이지 않았다. 프레임 밖에서 누군가의 팔이 두 번 들어왔다 나갔다. 그게 전부였다. 소리는 안 들어가는 기종이었다." },
    { t: "say", who: "haram", text: "…아, 각도.", expr: "worry" },
    { t: "say", who: "haram", text: "그래, 열람실은 사각지대지. 우린 안쪽에 있었으니까.", expr: "smile" },
    { t: "say", who: null, text: "내가 서 있는 자리가 좀 이상하긴 했다. 재생을 껐다." },
    { t: "say", who: null, text: "구석 캐비닛에 3년 전 졸업앨범이 꽂혀 있었다. 축제 페이지. 부스, 합창, 폐막식. 야외무대 사진은 한 장도 없었다." },
    { t: "say", who: "haram", text: "사진사가 그날 배터리 나갔나.", expr: "laugh" },
    { t: "say", who: null, text: "옆 장 단체사진, 뒷줄 오른쪽이 조금 벌어져 있었다. 원래 그런 구도인 줄 알았다." },
    { t: "say", who: null, text: "덮다가 문득, 3년 전에 나는 뭘 하고 있었지 싶었다. 봄부터 가을까지가 통째로 흐리다." },
    { t: "say", who: null, text: "나는 원래 기억력이 나쁘다. 중학교 3학년 봄 소풍이 어디였는지도 모른다. 뭐, 그런 사람도 있는 거지." },
    { t: "bg", src: "/assets/bg/bg_flowerbed.webp", fx: "fade" },
    { t: "say", who: null, text: "돌아가는 길, 본관 뒤 화단 앞에서 걸음이 멎었다. 흙이 다른 데보다 붉고 새것 같았다." },
    { t: "say", who: null, text: "순찰 도는 경비 아저씨가 옆을 지나갔다." },
    { t: "say", who: "haram", text: "아저씨, 여기 원래 무대였다면서요?", expr: "smile" },
    { t: "say", who: "mob", text: "…화단 예쁘지. 학생들이 잘 안 밟아줘서 다행이야.", expr: "neutral" },
    { t: "say", who: null, text: "아저씨는 그 말만 하고 갔다." },
    { t: "say", who: null, text: "이 학교 사람들은 저 자리 얘기를 안 한다. 안 하는 게 아니라, 못 하는 것 같기도 하고." },
    { t: "say", who: null, text: "뭐, 나만 몰라도 사는 데 지장은 없다." },
    { t: "set", ops: [{ key: FLAGS.CLUE_CCTV, op: "set", value: true }] },
    { t: "set", ops: [{ key: FLAGS.CLUE_ALBUM, op: "set", value: true }] },
    { t: "set", ops: [{ key: FLAGS.CLUE_FLOWERBED, op: "set", value: true }] },
    { t: "jump", scene: "c2s04" },
  ],
};
